### ISSUE TITLE
Why the 'id' field on json for coords?

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#30]
We never use those cs names in the page, and seems odd to put them there in general, doesn't it?

**Comment by mjneil** [comment]
Originally I was generating cs.wisc.edu emails from them but have been removed due to spam.

Also an enhancement I plan on adding but haven't yet, is to use the Coord id in the hours.json to index into the Coors list and get the full coord object on hours page to possibly add things like coord info for current coord holding office hours, etc.

**Comment by katamaritaco** [comment]
Alright, that's fair. I'm still going to keep mine as is, and then _that one_ can link to hours, etc/
