### ISSUE TITLE
Add The WebCam™

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#9]
Very necessary!

**Comment by mjneil** [comment]
Referring to the Access-Control-Allow-Origin issue pointed out by @zthomae, I think it would be a good idea if we could possibly find another location for the webcam that has a better complete view of the lab. We have to turn off the moving of the cam half the time anyway because people go onto the site and just whip it back and forth. The webcam isn't Willow Smith

**Comment by LOZORD** [comment]
niceme.me :+1: 

Maybe raise funds for multiple cameras? Although wiring them up would be a nightmare...

**Comment by katamaritaco** [comment]
Personally, I don't think that whipping the camera back and forth has ever been a problem besides "WOW!!! >:[ These ANIMALS are ABUSING the CAM!!!!". 

If it is such a problem, just make the camera turn slower, so that it doesn't really do anything. Make a timer so you can only move it so much in a period. Many solutions rather than moving it, but :yolo: :100: :shit: :shit:

**Comment by melutzke** [comment]
The webcam code is in a repo and it should be easy(tm) to slow its roll.
